
server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.96.175.143:8848   #配置Nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'