
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTime=GMT%2B8&characterEncoding=utf-8&userSSL=false
    username: root
    password: root


