
#静态资源请求：默认无前缀     默认 META-INF/resources、public、resoures/resoures、static下的都是静态资源
#设置静态资源前缀访问：      res下的所有请求为静态资源请求，不建议设置，会影响index.html不能被默认访问
#spring:
#  mvc:
#    static-path-pattern: /res/**

#修改默认静态资源路径，修改后，静态资源只能放在haha下，否则访问无效
#  web:
#    resources:
#      static-locations: [classpath:/haha/]

#开启浏览器参数方式内容协商功能，可以自定义传给客户端是json还是xml数据
#Parameter策略优先确定是要返回json数据（获取请求头中的format的值)，前提是客户端支持哪些数据
    #http://localhost:8080/test/person?format=xml  或  http://localhost:8080/test/person?format=json
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#修改服务器前置路径，之后的所有请求必须以/world开始
server:
  servlet:
    context-path: /world



#REST  default：true
#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true







