
server:
  port: 8401

spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
        #server-addr: 47.96.175.143:8848 #Nacos服务注册中心地址
    sentinel:
      transport:      #配置Sentinel dashboard地址，默认8719端口，若被占用会自动从8719开始依次 +1扫描，直到找到未被占用的端口
        dashboard: localhost:8085
        #dashboard: 47.96.175.143:8080
        port: 8719
        #clientIp: 47.96.175.143

      web-context-unify: false # 关闭context整合

      #sentinel持久化
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow



management:
  endpoints:
    web:
      exposure:
        include: '*'

#激活Sentinel对Feign支持
feign:
  sentinel:
    enabled: true




